global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # --- THIS IS THE IMPORTANT CHANGE ---
  # It now uses the Docker service name 'scylla' to find the database.
  - job_name: 'scylla'
    static_configs:
      - targets: ['scylla:9180'] # Scylla metrics port
        labels:
          cluster: 'local-scylla-cluster'