global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644'] # Port 9644 is the admin API containing metrics
    metrics_path: /metrics


  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'scylla'
    static_configs:
      - targets: ['scylla:9180']
        labels:
          cluster: 'local-scylla-cluster'