[package]
name = "arachne"
version = "0.1.0"
edition = "2024"
default-run = "seeder"

[[bin]]
name="stress-test-kafka"
path = "src/kafka_stress_test.rs"

[[bin]]
name="seeder"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12.5", features = ["json", "gzip", "brotli", "deflate", "stream", "cookies", "native-tls", "hickory-dns"] } # Added brotli for better compression support
wreq = { version = "*"}
wreq-util = "*"
scraper = "0.19.0"
tokio = { version = "1.38.0", features = ["full"] }
url = "2.5.2"
# robotstxt = "0.12.0" # We'll keep this commented for now as requested, but it's vital for a real-world crawler
futures = "0.3.30"
anyhow = "1.0.86"
serde = { version = "1.0", features = ["derive"] } # For saving/loading state
serde_json = "1.0" # For JSON format
sha2 = "0.10.8" # To create unique filenames from URLs
hex = "0.4.3" # To format the hash for filenames
openssl = { version = "*", features = ["vendored"] }
rdkafka = { version = "*", features = ["cmake-build", "zstd"] }
chrono = "0.4.41"
dotenvy = "0.15.7"
robotparser = "0.11"
thiserror = "1.0"
scylla = { version = "*", features=["chrono-04"]}
rand = "0.9.2"
csv = "1.4.0"
flate2 = "1.1.5"
[target.'cfg(not(target_os = "windows"))'.dependencies]
tikv-jemallocator = "*"
[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { version = "*", default-features = false  }
futures-util = "0.3"
bytes = "1.5"

# Parquet & Arrow (The gold standard for efficiency)
parquet = { version = "54.0", features = ["async", "snap"] }
arrow = "54.0"
arrow-array = "54.0"
arrow-schema = "54.0"
ego-tree = "*"
chrono = "0.4.39"
